### ISSUE TITLE
Paste into expressions

### ISSUE THREAD

**Issue by ProfZijlstra** [mzijlstra/flowcharts#32]
When pasting into expressions the input field doesn't resize until you hit a key.

Change inputHere boxse to resize based oninput event instead of onkeypress

**Comment by mzijlstra** [comment]
Updated the code so that it resizes oninput (HTML5 event, not jQuery)

Also made output and call boxes actually evaluate the expression to check if it was valid, regardless of the type it may have (both support any type)
